1\. **PCA on 3D dataset**

* Generate a dataset with 3 features each with N entries (N being ${\cal O}(1000)$). With $N(\mu,\sigma)$ the normali distribution with mean $\mu$ and $\sigma$  standard deviation, generate the 3 variables $x_{1,2,3}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
* Find the eigenvectors and eigenvalues using SVD. Check that the two procedures yield to same result
* What percent of the total dataset's variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained.
* Redefine the data in the basis yielded by the PCA procedure
* Plot the data points in the original and the new coordiantes as a set of scatter plots. Your final figure should have 2 rows of 3 plots each, where the columns show the (0,1), (0,2) and (1,2) proejctions.


In [2]:
import numpy as np
from numpy import random as npr
import pandas as pd
from scipy import linalg as la
from matplotlib import pyplot as plt
%matplotlib inline

In [47]:
# create dataset
npr.seed(42069)
max_N = 4269
dataFrame = pd.DataFrame( npr.normal( 0, 1, max_N ), index=np.arange(max_N), columns=['x_1'])
dataFrame['x_2'] = dataFrame['x_1'] + npr.normal( 0, 3, max_N )
dataFrame['x_3'] = 2.*dataFrame['x_1'] + dataFrame['x_2']

# CENTERING TO 0 TO ALLOW BETTER STATISTICS
mean_1 = dataFrame['x_1'].mean()
mean_2 = dataFrame['x_2'].mean()
mean_3 = dataFrame['x_3'].mean()
dataFrame['x_1'] -= mean_1
dataFrame['x_2'] -= mean_2
dataFrame['x_3'] -= mean_3
dataFrame.describe()

x_1           x_2           x_3
count  4.269000e+03  4.269000e+03  4.269000e+03
mean   2.236570e-17  6.865750e-18 -1.614492e-16
std    1.005070e+00  3.095394e+00  4.194858e+00
min   -3.332416e+00 -1.144961e+01 -1.592870e+01
25%   -6.956393e-01 -2.075407e+00 -2.819554e+00
50%    7.761077e-03 -3.007563e-02 -1.057632e-01
75%    6.650257e-01  2.082020e+00  2.806803e+00
max    3.674083e+00  1.129946e+01  1.423102e+01

In [68]:
# find covariance matrix and its eigenvector/eigenvalues
cov = dataFrame.cov()
l, V = la.eig(cov)
# to return into real world
#np.real_if_close(l)
print(l)
print(V)

# find eigenvectors/values using SVD
U, spectrum, Vt = la.svd(dataFrame.T)
l_svd = np.power(spectrum, 2)/(max_N-1)
V_svd = U
print(l_svd)
print(V_svd)

# differences compute and output
#l_diff = np.real_if_close(l) - l_svd
#V_diff = np.real_if_close(V) - V_svd
#print(l_diff)
#print(V_diff)

# they are mostly the same, not considering underflow values
# also, one is ordered, the other one not

Lambda = np.diag(l)
trace =  np.trace(cov)
t_frac = np.real_if_close(l)/trace
np.set_printoptions(suppress=True)
print(f"Partial weight of each eigenvalue: {t_frac}")
print(f"Partial weight of eigenvalues 0,2: {(t_frac[0]+t_frac[2])*100:.13f}%")

# redefine data in procedure pf PCA
#r_frame = pd.DataFrame(, index=np.arange(max_N), colums=['p_1', 'p_2'])

[26.19788937+0.j  0.        +0.j  1.99057311+0.j]
[[-0.11966483 -0.81649658  0.56481294]
 [-0.57208693 -0.40824829 -0.71137183]
 [-0.81141659  0.40824829  0.41825406]]
[26.19788937  1.99057311  0.        ]
[[-0.11966483  0.56481294 -0.81649658]
 [-0.57208693 -0.71137183 -0.40824829]
 [-0.81141659  0.41825406  0.40824829]]
Partial weight of each eigenvalue: [0.92938341 0.         0.07061659]
Partial weight of eigenvalues 0,2: 99.9999999999999%


2\. **PCA on a nD dataset**

Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normal distributed, with standar deviation much smaller (say, a factor 50) than those used to generate the $x_1$ and $x_2$.

Repeat the PCA procedure and compare the results with what you obtained before

3 \. **Looking at an oscillating spring** (optional)

Imagine you have $n$ cameras looking at a spring oscillating along the $x$ axis. Each  camera record the motion of the spring looking at it along a given direction defined by the pair $(\theta_i, \phi_i)$, the angles in spherical coordinates. 

Start from the simulation of the records (say ${\cal O}(1000)$) of the spring's motion along the x axis, assuming a little random noise affects the measurements along the $y$. Rotate such dataset to emulate the records of each camera.

Perform a Principal Component Analysis on the thus obtained dataset, aiming at finding the only one coordinate that really matters.


4\. **PCA on the MAGIC dataset** (optional)

Perform a PCA on the magic04.data dataset

In [ ]:
# get the dataset and its description on the proper data directory
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data -P ~/data/
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.names -P ~/data/ 